### PR TITLE
Embed Channel 9 video

### PR DESCRIPTION
**Pull request by terrajobst**
@conniey @twsouthwick

### CODE REVIEW

**Comment by conniey** [comment]
LGTM :+1: Thanks! :D

**Comment by terrajobst** [comment]
Is there anything more needed I should I just hit merge?

Also, how long will it take to be live?

**Comment by twsouthwick** [comment]
We had it automatically deploying, but it's been broken since we updated to beta8 and then rc1 of ASP.NET Core due to aspnet/dnx#3192. I'll manually deploy it for now.

**Comment by terrajobst** [comment]
Sweet. Thanks!

**Pull request merged**
